version: '3'
services:
  my_mongodb:
    image: mongo:4.4  # Specify MongoDB version 4.4
    ports:
      - "27018:27017"

  my_flaskapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - my_mongodb
