# Use the official MongoDB image as the base image
FROM mongo:4.0.8

# Copy the initialization script into the container
COPY init.js /docker-entrypoint-initdb.d/

# Define environment variables for MongoDB database and credentials
ENV MONGO_INITDB_DATABASE=ProfileApp

# Expose MongoDB port
EXPOSE 27017

CMD ["mongod", "--replSet", "rs0", "--bind_ip_all"]
