
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
data:
  mongodb.conf: |
    storage:
      dbPath: /data/db
    replication:
      replSetName: "rs0"
immutable: true

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
provisioner: k8s.io/minikube-hostpath
volumeBindingMode: Immediate
reclaimPolicy: Delete

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-profilewebapp
  labels:
    app: mongo-profilewebapp
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    app: mongo-profilewebapp

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-profilewebapp
  labels:
    app: mongo-profilewebapp
spec:
  serviceName: "mongo-profilewebapp"
  replicas: 3
  selector:
    matchLabels:
      app: mongo-profilewebapp
  template:
    metadata:
      labels:
        app: mongo-profilewebapp
    spec:
      containers:
      - name: mongo
        image: godfrey22152/mongo-profilewebapp:5.0
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
        - name: mongodb-config
          mountPath: /etc/mongo
        env:
        - name: MONGO_INITDB_DATABASE
          value: "ProfileApp"
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - mongo --eval "db.adminCommand('ping')"
          initialDelaySeconds: 5
          periodSeconds: 300
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - mongo --eval "db.adminCommand('ping')"
          initialDelaySeconds: 5
          periodSeconds: 300
        args:
        - --config=/etc/mongo/mongodb.conf
      volumes:
        - name: mongodb-config
          configMap:
            name: mongodb-config
            items:
              - key: mongodb.conf
                path: mongodb.conf
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi

